/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutMe {
  'bio' : string,
  'contactInfo' : ContactInfo,
  'skills' : Array<Skill>,
}
export interface ContactInfo {
  'linkedin' : string,
  'email' : string,
  'website' : string,

  'github' : string,
}
export interface Experience {
  'duration' : string,
  'role' : string,
  'description' : string,
  'company' : string,
}
export interface Interest { 'name' : string, 'description' : string }
export interface Portfolio {
  'aboutMe' : AboutMe,
  'projects' : Array<Project>,
  'interests' : Array<Interest>,
  'experiences' : Array<Experience>,
  'achievements' : Array<achievements>,
}
export interface Project {
  'link' : string,
  'name' : string,
  'description' : string,
  'techStack' : Array<string>,
}
export interface Skill { 'name' : string, 'detail' : string }
export interface _SERVICE {
  'addExperience' : ActorMethod<[Experience], undefined>,
  'addInterest' : ActorMethod<[Interest], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'getAboutMe' : ActorMethod<[], AboutMe>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getInterests' : ActorMethod<[], Array<Interest>>,
  'getPortfolio' : ActorMethod<[], Portfolio>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'updateAboutMe' : ActorMethod<[AboutMe], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];